cataclysmroguelikegallery/Cata-Rogall-Modpack

BN/Jakes_Squirrel_mod/advtech/sq_nano_tools.json

기존의 레시피 (나사 돌리기 1단계, 고철 1, 플라스틱 조각 1)에서
현재의 레시피(나사 돌리기 1단계, 절단 1단계, 납땜용 인두 10, 핫플레이트류 5, 고철 1, 플라스틱 조각 1)로 수정.

202304051014 다람쥐 모드 기압계 레시피 수정

---

DDA/README.md

README.md 추가

---

BN/Jakes_Squirrel_mod/advtech/sq_advanced_armor.json

202304212033 다람쥐 모드 작은 패치

---

BN/Jakes_Squirrel_mod/items/sq_shields.json

202305011614 다람쥐 모드 긴급패치

---

BN/Jakes_Squirrel_mod/items/sq_shields.json

202305011621  다람쥐모드 또 긴급패치

---

BN/Jakes_Squirrel_mod/advtech/sq_advanced_armor.json

> 눈 아픈 초록초록한 광증폭시야 대신 착용시 20칸의 야간시야를 부여하는 "투과성 스캐너 시스템" 변이를 얻게 함
> 작동시 NO_TAKEOFF 태그 추가

202305011653 다람쥐 모드 파이어니어 패치

---

BN/Jakes_Squirrel_mod/advtech/sq_advanced_armor.json
BN/Jakes_Squirrel_mod/advtech/sq_carbon_stuffs.json

202305091554 다람쥐 모드 버그 수정

---

BN/ProjectSquirrel/advtech/sq_nano_tier.json

+ 모티프가 모티프인 만큼 손전등 기능도 추가하겟읍니다.

202305280201 프로젝트: 다람쥐 핫픽스

---

BN/ProjectSquirrel/advtech/sq_advanced_armor.json

202305280239 프로젝트: 다람쥐 워든 핫픽스

---

BN/ProjectSquirrel/items/sq_weapon_override.json

202305281832 프로젝트: 다람쥐 또 픽스

---

BN/ProjectSquirrel/advtech/sq_advanced_armor.json

202305291812 프로젝트: 다람쥐 핫픽스

---

BN/ProjectSquirrel/items/sq_nomex_survivor.json

202305292237 프로젝트: 다람쥐 핫픽스

---

BN/ProjectSquirrel/items/sq_nomex_survivor.json

202305292307 프로젝트: 다람쥐 핫픽스

---

BN/ProjectSquirrel/advtech/sq_main_tools.json
BN/ProjectSquirrel/advtech/sq_nano_generic_comp.json

202305301246 프로젝트: 다람쥐 버그 픽스

---

BN/ProjectSquirrel/advtech/sq_nano_tier.json

* 실험용 하드라이트 블레이드에 붙은 절단 1단계를 없애서 A로 빠르게 껐다켰다 가능해짐.
* 히트 블레이드의 레시피가 출력되지 않았던 문제 해결

202307250543 PPR bug fixes

---

BN/Reduced Temperature Effects/effects.json
BN/Reduced Temperature Effects/modinfo.json

온도로 인한 영향(열 감속, 피해, 각종 디버프 등)이 크게 줄어듭니다.
모드 깔면 난이도 탭에 있을거임
캐릭터가 더운 여름에 속도 쭉쭉 느려지고 쪄죽으려 하는 걸 크게 완화시켜줄거임.

202308231102 모드팩 업데이트

---

BN/overhull/flags_mutation.json

fix: mutation flags 추가

---

README.md

- fix: 깨진 링크 수정
- chore: Old_Ammo_Stats 링크 제거

fix: 깨진 링크 수정

---

BN/Must Survive/regional_map_settings.json
BN/ProjectSquirrel/advtech/sq_hardlight_fusion_and_gunmods.json
BN/ProjectSquirrel/spawns/sq_itemgroup.json

1. 가혹한세상: mx_city_trap 삭제함
2. 람쥐모드: 스피드로더 수정, 8발들이 레일 스피드로더 추가

202310031926 핫픽스

---

BN/Dogmeat's Mode/miscs/ITEM_armor.json

도그밋모드 업데이트
https://gall.dcinside.com/rlike/448907

202311050054 모드팩 업데이트

---

BN/ProjectSquirrel/advtech/sq_hardlight_fusion_and_gunmods.json

202311151823 프로젝트: 다람쥐 픽스

---

BN/ProjectSquirrel/mutations/item.json
BN/ProjectSquirrel/mutations/mutations.json
BN/ProjectSquirrel/mutations/sq_mutations_override.json
BN/Targeted Mutations_BN_KO/mutations.json

202311171827 프로젝트: 다람쥐 버그픽스

---

BN/Big_dogbot_64/tile/expgun.json
BN/Must Survive/ammo/nail.json
BN/ProjectSquirrel/advtech/sq_hardlight_fusion_and_gunmods.json
BN/SF_Weapons/Contents/SF_future_weapons.json
BN/SF_Weapons/Contents/SF_modern_weapons.json
DDA/blazemod(0.G)/items/guns/blaze_weapons.json
DDA/secronom(0.G)/secronom/Modification_Files/Items/secro_guns.json
DDA/secronom(0.G)/secronom_lore_expansion/Modification Files/Items/Armors/secro_power_armor_creation.json
DDA/secronom(0.G)/secronom_lore_expansion/Modification Files/Items/secro_ammo_mags.json

참고: https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3655

fix: `NON-FOULING` 플래그를 `NON_FOULING`로 변경

---

BN/ProjectSquirrel/items/sq_armor_override.json

~~버그리포트보다 더 빠르게 올립니다.~~
파워아머헬멧 사용시 스프라이트가 누락되는 문제를 해결합니다~

fix: 파워아머헬멧 스프라이트 누락

---

BN/ProjectSquirrel/items/sq_armor_override.json

#132 와 유사한 증상을 추가로 발견하여 고쳤습니다.

fix: 다른 헬멧들 스프라이트 누락

---

BN/Dogmeat's Mode/flags.json
BN/Dogmeat's Mode/inventory/ITEM_molle.json

- fixes #134 
참고: https://docs.cataclysmbn.org/ko/mod/json/explanation/loading_order/#_top

fix: 사용 전에 `MOLLE` 플래그를 선언

---

BN/ProjectSquirrel/advtech/sq_nano_generic_comp.json

https://github.com/NobleJake/ProjectPackRat/pull/7

fix: Superalloy Plating's Vanilla Recipe Being Overridden

---

BN/Big_dogbot_64/tile/power_armor.json

Delete MOLLE flag from power armor in Big_dog mod

---

BN/SF_Weapons/Contents/SF_future_weapons.json

silver는 material id, silver_small은 item id 였음 ㄷㄷ

fix: `silver` -> `silver_small`
